version: '3.8'
services:
  train:
    image: mulaniirfanftc/train1:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  recharge:
    image: mulaniirfanftc/recharge1:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: mulaniirfanftc/dth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
